### ISSUE TITLE
How to tell if data are downloaded correctly?

### ISSUE THREAD

**Issue by mikeda100** [Bayes-Song/Open-Llama#5]
Downloading Pile and Wudao data needs a lot of time. During this long time period, network connection can break and various types of errors can occur.

For example, I am getting the following error message and not sure if it is okay:
"curl: (92) HTTP/2 stream 0 was not closed cleanly: PROTOCOAL_ERROR(err 1)"

Is there a way to double-check and ensure the data are downloaded correctly?

**Comment by Bayes-Song** [comment]
The easiest way is to run the download script again, as it is set up to automatically resume the download using the -C flag. If the download was not completed correctly previously, it will resume automatically. You can also check the remaining download amount, and if it shows 0, then the corresponding part is downloaded successfully. Additionally, you can calculate the hash value, and I will provide the hash value for each data later to facilitate verification.

**Comment by Bayes-Song** [comment]
sha256sum for the pile https://the-eye.eu/public/AI/pile/SHA256SUMS.txt
md5sum for WuDaoCorpus2.0_base_200G.rar fc90a7799cefffff324965e5bfc83917

Interruptions during data downloads can be very annoying, and it may be better to split the downloading and preprocessing into two separate steps.

**Comment by mikeda100** [comment]
python3 data/preprocess_the_pile.py
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [01:33<00:00,  3.12s/it]
total line: 1557049
total files: 95
**

**Comment by Bayes-Song** [comment]
那确实是不完整的，总行数应该有2亿行以上，多运行几次上面的下载命令，如果剩余都是0了再处理吧

**Comment by mikeda100** [comment]
okay thanks a lot!

**Comment by mikeda100** [comment]
What about the pile?

Are the following correct?

------------------------------------------------- 

python3 data/preprocess_the_pile.py
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 32/32 [3:26:34<00:00, 387.31s/it]
total line: 211036982
total files: 12880

**Comment by s-JoL** [comment]
> 

This is even more data than I have, so it's possible that I haven't downloaded it completely.

**Comment by mikeda100** [comment]
I think it might be the case that I have also included the pile data's "validation" and "testing" files...  while you probably only used the files under the train directory.
